M48
; DRILL file {KiCad (6.0.1)} date Mon Jan  9 12:57:26 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-09T12:57:26+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X14.353Y-14.478
X14.353Y-17.018
X14.353Y-20.32
X14.353Y-22.86
T0
M30
