M48
; DRILL file {KiCad (6.0.1)} date Tue Feb 14 09:31:44 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-14T09:31:44+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X2.286Y-2.281
X2.286Y-4.821
X2.286Y-8.123
X2.286Y-10.663
T0
M30
